<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Generate</title>
    <style media="screen">
      a {
        text-decoration: none;
        font-size: 1.6rem;
        font-weight: bold;
      }

      .container {
        max-width: 50%;
        margin-top: 10%;
        margin-left: auto;
        margin-right: auto;
      }

      .text {
        text-align: justify;
      }

      @media (max-width: 768px) {
        .container {
          max-width: 90%;
          width: auto;
        }
      }
    </style>
  </head>
  <body>
    <div class="container">
      <a href="javascript:history.go(-1)">← Atrás</a>
      <p class="text">EL CLUB GENERATE, ES UNA FINTECH BAJO LA FIGURA Y ESPIRITU DE UNA ASOSIACION CIVIL SIN FINES DE LUCRO, QUE TE PERMITE REALIZAR TUS PROYECTOS PRODUCTIVOS, SER DUEÑO DE TU TRABAJO, CONVERTIRTE EN EMPRESARIO DE TUS IDEAS, SER INVERSOR Y PENSAR EN TU FUTURO FINANCIERO COMO ACCIONISTA DE PROYECTOS DENTRO DE LA ECONOMIA REAL, MEDIANTE CREDITOS PARA DESARROLLOS NUEVOS Y EMPRESAS QUE NECESITEN APALCANRSE, AYUDA A EMPRENDEDORES Y EMPRESARIOS, PROPORCIONA MICRO CREDITO PERSONALES.
  ¿CUALES SON LOS BENEFICIOS DE PERTENCER AL CLUB?
  COMO CUALQUIER CLUB, ESTE COBRARA UNA CUOTA POR SER SOCIO, DICHA CUOTA SERA ANUAL, Y SE PODRA PAGAR EN 1 PAGO O VARIOS CON TARJETA DE CREDITO, ESTA CUOTA SERA ADMNISTRADA POR EL CLUB PARA REALIZAR LOS DIFERENTES CREDITOS, LOS CUALES SERAN VOTADOS POR LOS SOCIOS ACTIVOS.
  TAMBIEN ADMINISTRAMOS UN FONDO PARA LOS SOCIOS QUE NECESITEN AYUDA EN CUETIONES DE SALUD DONDE NINGUN ORGANISMO LES DE RESPUESTA.
  ADMINISTRAMOS UN PRESUPUESTO DE RECOMPENZA PARA LOS SOCIOS QUE GENEREN MAS SOCIOS.
  LA ADMNISTRACION SERA TRANSPARENTE Y SE PUBLICARA UN PRESUPUESTO MENSUAL Y EL RESULTADO AL CIERRRE DEL MES, PARA QUE TODOS LOS SOCIOS TENGA ACCESO Y PODER SABER QUE HACE LA ASOSIACON CON SU DINERO.
  COMO ACCEDER A LOS CREDITOS, A LA RECOMPENZA POR SOCIOS, Y COMO FUNCIONA CADA TEMA, PODRAS VERLO DENTRO DE LA PLATAFORMA, CADA ITEM TENDRA UNA EXPLICACION.
  PARA ANOTARTE DEBES SEGUIR LOS PASOS Y COMPLETAR EL REGISTRO, UNA VEZ QUE TERMINES ESTE PASO, PAGARAS TU MEMBRESIA ANUAL SEGUN LAS FORMAS DISPONIBLES.
  TE INVITAMOS A QUE ENTRES EN CADA SEGMENTO Y TE INFORMES DE LOS BENEFICIOS Y POSIBILIDADES, ANIMATE A FORMAR PARTE DE ESTA IDEA.</p>
    </div>
  </body>
</html>
